version: '3.6'

networks:
  fortune_web-internal:
  fortune_web-external:
    name: fortune_web-external
    external: true

volumes:
  dbdata:

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: fortune_web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - dbdata:/var/lib/postgresql/data/
    networks:
      - fortune_web-internal
    ports:
      - "9432:5432"

  # main application
  app:
    env_file:
      .env
    build:
      dockerfile: ./Dockerfile
      context: .
    command: bash -c "./start.sh"
    environment:
      ENVIRONMENT: "development"
    depends_on:
      - db
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    networks:
      - fortune_web-internal
      - fortune_web-external
