# Generated by Django 5.0.7 on 2024-07-14 10:07
import codecs
import re

from django.db import migrations


def populate_fortunes(apps, schema_editor):
    Fortune = apps.get_model("fortunes", "Fortune")

    fortune_file = "fortunes.txt"
    with codecs.open(fortune_file, mode="r", encoding="utf-8") as f:
        contents = f.read()

    lines = [line.rstrip() for line in contents.split("\n")]

    delim = re.compile(r"^%$")

    fortune_objects = []
    cur = []

    def save_if_nonempty(buf):
        fortune = "\n".join(buf)
        if fortune.strip():
            fortune_objects.append(Fortune(text=fortune))

    for line in lines:
        if delim.match(line):
            save_if_nonempty(cur)
            cur = []
            continue

        cur.append(line)

    if cur:
        save_if_nonempty(cur)

    Fortune.objects.bulk_create(fortune_objects)


def delete_fortunes(apps, schema_editor):
    Fortune = apps.get_model("fortunes", "Fortune")
    Fortune.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('fortunes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            populate_fortunes,
            reverse_code=delete_fortunes,
        ),
    ]
